jsprofile/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('', index, name='index'),
]

story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jsprofile.urls')),
    path('search/', include('story8.urls')),
    path('story9/', include('story9.urls')),
]

story8/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import search

urlpatterns = [
    path('', search, name='search'),
]

story9/urls.py
from django.urls import path
from .views import home, func_login, func_logout

app_name = "story9"

urlpatterns = [
    path('', home, name= 'home'),
    path('login/', func_login, name = 'login'),
    path('logout/', func_logout, name = 'logout'),
]

jsprofile/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

jsprofile/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    argument={

    }
    return render(request, 'index.html', argument)

story8/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

# Create your views here.
def search(request):
    argument={
    }
    return render(request, 'search.html', argument)

story9/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required(login_url='story9:login')
def home(request):
    user = request.user
    return render(request, 'story9.html', {'user':user})

def func_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('story9:home')
    else :
        if request.user.is_authenticated:
            return redirect('story9:home')
        else:
            form = AuthenticationForm()
    return render(request, 'login.html', {'form':form})

def func_logout(request):
    logout(request)
    return redirect('story9:login')

jsprofile/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>syk.</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
    <link type="text/css" rel="stylesheet" href="../static/css/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="../static/js/script.js"></script>

</head>

<body class="ganti"> 
  <header>
    <div class="row">
        <label class="switch" id="pencet">
            <input type="checkbox">
            <span class="slider round" id="dark_theme"></span>
        </label>
        <h4 style="margin-left: 1%;">Dark Mode</h4>
    </div>
    <div class="foto">
        <img src="../static/img/profil.jpg" >
    </div>
    <h3 class="text-center" style="padding-bottom: 1%;">Muhammad Alfi Syakir</h3>
  </header>
  <section>
    <div id="container" class="ganti" >


        <div id="accordion" class="accord" >
            <h3 class="atasan">Aktivitas</h3>
            <div class="ganti">
                <p>
                Aktivitas saya saat ini adalah saya mempunyai kesibukan yaitu berkuliah di Fasilkom UI semester 3.
                Selain itu, saya sekarang sedang aktif dalam berorganisasi dan kepanitian sebagai kegiatan kedua saya
                selain kegiatan akademis.
                </p>
            </div>
                    
            <h3 class="atasan">Pengalaman Organisasi/ Kepanitiaan</h3>
            <div class="ganti">
                <p>
                Saya memiliki beberapa pengalaman organisasi/ kepanitian selama masa SMA sampai kuliah saat ini, diantaranya:
                </p>
                <ul>
                <li>PIC of Information, Communication, and Pers at Rohis of SMAN 1 Purworejo 2017</li>
                <li>VPIC of Logistic at SIGEMPUR UI 2019</li>
                <li>Staff of Public Relation at KOMPOR UI 2019</li>
                <li>Staff of Public Relation at FUKI Fasilkom UI 2019</li>
                <li>Staff of Startup Academy at COMPFEST 11</li>
                <li>Staff of Danus at PMB Fasilkom UI 2019</li>
                <li>PIC of Seminar and Talkshow at Educare 2020</li>
                <li>PIC of Public Relation, Publication, Documentation, and Design at SIGEMPUR UI 2020</li>
                <li>PIC of HRD of Academy at COMPFEST 12</li>
                </ul>
            </div>
                    
            <h3 class="atasan">Prestasi</h3>
            <div class="ganti">
                <ul>
                    <li>4th Place at KRENOVA (Kreasi dan Inovasi Masyarakat) 2017</li>
                </ul>
            </div>
        </div>
    </div>
  </section>    
</body>
</html>

story8/templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SEARCH BOOK</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link type="text/css" rel="stylesheet" href="../static/css/style.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="../static/js/search.js"></script>
</head>

<body style="background-color: mediumaquamarine;">
    <header>
        <div class="container">
            <h1 class="text-center">Cari Buku?</h1>
            <div class="form-inline search">
                <input class="form-control form-control-sm mr-3 w-100 text-align-center" id="search" type="text" placeholder="Ketik judul buku yang kamu cari di sini..." aria-label="Search" autocomplete="off">
            </div>
        </div>
    </header>
    <section style="padding: 2%;">
        <h3 class="text-center">Hasil Pencarian</h3>
        <table class="table table-active table-hover" style="width: 80vw;  display: block; margin: auto;" id="hasil">
        </table>
    </section>
</body>

</html>

story9/templates/login.html
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <title>Login</title>
    </head>
    <body style="background-color: mediumaquamarine;">
        <section style="padding: 10%;">
            <h3 class="text-center">Login</h3>
            <h6 class="text-center" style="color: darkred;">masukkan</h6>
            <p class="text-center">username: cobagratis | password : hanyacoba</p>
            <div>
                <form action="{% url 'story9:login' %}" method = "POST" class="text-center">
                    {% csrf_token %}
                    {{ form.username.label }}
                    <div style="display: block; margin: auto;">
                        {{ form.username }}
                    </div>
                    {{ form.password.label }}
                    <div style="display: block; margin: auto;">
                        {{ form.password }}
                    </div>
                    <div style="padding-top: 2%;">
                        <input class="button btn btn-primary text-center" type="submit" value="Login">
                    </div>
                </form>
            </div>
        </section>
    </body>
</html>

story9/templates/story9.html
{% load static %}

<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <title>Welcome</title>
    </head>
    <body style="background-color: mediumaquamarine;">
        <h1 class="text-center" style="padding-top: 5%;">Hallo, {{ user.first_name }} !</h1>
        <div>
            <img src="../static/img/halo.jpg" style="max-width: 250px; display: block; margin: auto;">
        </div>
        <a href="{% url 'story9:logout' %}" >
            <div style="padding-top: 1%;">
                <input class="button btn btn-danger text-center" style="display: block; margin: auto;" type="submit" value="Logout">
            </div>
            <!-- <h4 class="text-center" style="color: white;">
                logout
            </h4> -->
        </a>
    </body>
</html>